name: 'Unity - Request Activation File'
author: Webber Takken <webber@takken.io>
description: 'Request the manual activation file for acquiring a Unity personal license.'
inputs:
  unityVersion:
    required: false
    default: '2019.2.11f1'
    description: 'Version of unity to use for building the project.'
  customImage:
    required: false
    default: ''
    description: 'Specific docker image that should be used to request activation file'
outputs:
  filePath:
    description: 'Path of the manual activation file'
branding:
  icon: 'box'
  color: 'gray-dark'
runs:
  using: 'node12'
  main: 'action/index.js'
